### ISSUE TITLE
When main.css is included it doesn't works

### ISSUE THREAD

**Issue by azharmehmood** [nicksenger/react-arcgis#22]
Hi,
I am trying to integrate react-arcgis with my application.
When i try to create map with out main.css it works fine but the styles are not applied. To apply styles when i include the main.css file https://js.arcgis.com/4.4/esri/css/main.css the application doesn;t load map and it wont show any error aswell.

Am i missing something. please help me out.

**Comment by nicksenger** [comment]
Hi @azharmehmood 

I haven't seen this issue before, and will probably need a bit more information in order to help you get it working. Is the app doing anything aside from rendering the map? Have you tried making just a bare-bones map app in order to see if the map works without the rest of your application?

If not, follow the readme in this repository that I made recently which renders a simple map, and let me know if that works:

[https://github.com/nicksenger/js-test-react-arcgis](https://github.com/nicksenger/js-test-react-arcgis)

Nick

**Comment by azharmehmood** [comment]
What i was doing 
<div>
<Map />
</div>

What i needed to do 
<div style={{ width: '800px', height: '600px' }}>
<Map />
</div>

And it started working... May be it checks for container hardcoded width and height before loading all assets.

I am new to arcgis so its a black box for me...

**Comment by azharmehmood** [comment]
Thanks for your help...

**Comment by nicksenger** [comment]
No problem! I'm glad you got it working. By default the map has width and height set to 100%, so needs to be rendered in a container with an explicit width/height otherwise it wont show up. Alternatively, you can specify a width/height directly on the map in the JSX using className or style props.
