### ISSUE TITLE
Can I use custom tile images with this?

### ISSUE THREAD

**Issue by mraak** [nicksenger/react-arcgis#34]
I have tile images in GEOREF format. Can I use them with this and is there some sort of converter between GEOREF and whatever format arcgis is using?

**Comment by nicksenger** [comment]
@mraak , I'm not personally familiar with the GEOREF format, but if it's supported by the ArcGIS JavaScript API then there is nothing preventing you from using it with react-arcgis.

I suggest you take a look in the [documentation for the ArcGIS JS API](https://developers.arcgis.com/javascript/latest/api-reference/index.html) to see if your format is supported.

Going to close this for now since it is not an issue with the library.
