### ISSUE TITLE
[esri.core.Promise] DEPRECATED: then() -- use .when(callback, errback) instead

### ISSUE THREAD

**Issue by ryanjeremy** [nicksenger/react-arcgis#41]
Since v.3.1.0, I'm getting a bunch of these console errors:

`[esri.core.Promise] DEPRECATED: then() -- use .when(callback, errback) instead`

This happens even when just rendering a map component and the error gets spammed over and over when implementing a promise. When I revert the package to version 3.0.0, it is fine and the error doesn't occur at all.

BTW - Thanks for the package though! It's great :)

**Comment by nicksenger** [comment]
Hey @ryanjeremy , this warning is happening because of some changes made to the ArcGIS JS API that I forgot to account for when updating the package >.<

I'll release a patch for this very soon!

**Comment by nicksenger** [comment]
Okay it seems like some things internal the the JS API are using `.then` despite it being deprecated, so the warning gets logged regardless of what you do from outside of the API.

The way to disable this warning message is to add the following to your dojoConfig:

```js
has: {
  “esri-promise-compatibility-deprecation-warnings”: 0
}
```

You can do this by invoking `esriPromise()` with this option set **_before_** your first react-arcgis component is mounted.

Here is an example entrypoint to your application:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import TestComponent from './testComponent';
import { esriPromise } from 'react-arcgis';

const config = {
  dojoConfig: {
    has: {
      "esri-promise-compatibility-deprecation-warnings": 0
    }
  }
};

esriPromise([], config).then(() => {
  ReactDOM.render(
    <TestComponent />,
    document.getElementById('react-container')
  );
});
```

Going to close this since it's not really an issue with the react-arcgis library.

**Comment by Kenigmatic** [comment]
@nicksenger , the code you suggested above didn't work for me. However, adding the following to my index.html silenced the deprecation warnings:

` <script>
  var dojoConfig = {
    has: {
      "esri-promise-compatibility": 1
    }
  };
</script> `

Add the above _**before**_ referencing arcgis . . .
` <link rel="stylesheet" href="https://js.arcgis.com/4.6/esri/css/main.css">
 <script src="https://js.arcgis.com/4.6/"></script> `

I found this info in the following posting: [ArcGIS Making Better Promises](https://blogs.esri.com/esri/arcgis/2017/12/14/making-better-promises/)

I think you are correct that the offending code is somewhere within the arcgis JS API.

Thanks for creating react-arcgis!
